name: raccoon
description: A complete and powerful flutter framework.
version: 1.0.0
homepage: https://github.com/hokamc/raccoon

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^1.6.24
  package_info: ^0.4.3+2
  device_info: ^1.0.0
  easy_localization: ^2.3.3
  device_preview: ^0.5.5
  purchases_flutter: ^1.4.3
  animate_do: ^1.7.3
  shared_preferences: ^0.5.12+4
  line_icons: ^0.2.0
  url_launcher: ^5.7.10
  connectivity: ^2.0.2
  # ad
  facebook_audience_network: ^0.7.1
  adsunity: ^1.0.3
  # dio
  dio: ^3.0.10
  dio_firebase_performance: ^0.2.0
  #  firebase free services *change carefully
  firebase_core: ^0.5.2
  firebase_analytics: ^6.2.0
  firebase_crashlytics: ^0.2.3
  firebase_performance: ^0.4.2
  firebase_remote_config: ^0.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - images/
    - fonts/Ubuntu/

  fonts:
    - family: Ubuntu
      fonts:
        - asset: fonts/Ubuntu/Ubuntu-Bold.ttf
        - asset: fonts/Ubuntu/Ubuntu-Medium.ttf
        - asset: fonts/Ubuntu/Ubuntu-Regular.ttf
        - asset: fonts/Ubuntu/Ubuntu-Light.ttf
        # italic
        - asset: fonts/Ubuntu/Ubuntu-BoldItalic.ttf
          style: italic
        - asset: fonts/Ubuntu/Ubuntu-MediumItalic.ttf
          style: italic
        - asset: fonts/Ubuntu/Ubuntu-Italic.ttf
          style: italic
        - asset: fonts/Ubuntu/Ubuntu-LightItalic.ttf
          style: italic